/* Golden-fixture tests. The fixture bodies came from running the ORIGINAL
 * configurator page's builder logic, so these pin extraction fidelity: for
 * identical inputs, lib/builder.js must reproduce that output byte for byte,
 * now wrapped in the output-style frontmatter the plugin installs. The rev and
 * docsPath parameters are the only intended divergences. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildOutputStyle, buildChatPreferences, buildPaletteMarkdown, sanitizeName } from '../lib/builder.js';

const here = dirname(fileURLToPath(import.meta.url));
const fix = (name) => readFileSync(join(here, 'fixtures', name), 'utf8');

const base = {
  name: 'Dave',
  weather: true, forecast: true, tasks: true, docs: true, fold: true,
  decision: true, diff: true, emdash: true, visual: true, interactive: true,
  dlg: 'blockers',
};
const cases = {
  'defaults': { ...base },
  'weather-off': { ...base, weather: false },
  'forecast-off': { ...base, forecast: false },
  'custom-name': { ...base, name: 'Alex', docs: false, dlg: 'free' },
  'dlg-ban': { ...base, dlg: 'ban', tasks: false },
};
const customRules = [
  'Ship notes. When a change lands, name the branch and say whether CI is green.',
  'Never guess at pricing or quotas: look the number up and cite the line you read it from.',
];
const styleCases = { ...cases, 'custom-rules': { ...base, custom: customRules } };

/* The output style is the only carrier the plugin installs, so its whole file
 * (frontmatter, generated-file stamp, contract body) is what gets pinned. */
for (const [key, cfg] of Object.entries(styleCases)) {
  test('output style fidelity: ' + key, () => {
    assert.equal(buildOutputStyle(cfg), fix(key + '.output-style.md'));
  });
}

for (const [key, cfg] of Object.entries(cases)) {
  test('chat preferences fidelity: ' + key, () => {
    assert.equal(buildChatPreferences(cfg), fix(key + '.chat-prefs.txt'));
  });
}

test('no marker machinery survives in the generated style', () => {
  const s = buildOutputStyle(base);
  assert.ok(!s.includes('BEGIN presentation-contract'));
  assert.ok(!s.includes('END presentation-contract'));
  assert.ok(s.includes('\n\n## Talking to Dave (presentation contract)\n'));
});

test('the output style frontmatter keeps the coding instructions', () => {
  const s = buildOutputStyle(base);
  assert.ok(s.startsWith('---\nname: talking-to-dave\n'));
  assert.match(s, /^keep-coding-instructions: true$/m);
});

test('custom rules continue the numbering and go in verbatim', () => {
  const plain = buildOutputStyle(base);
  assert.equal(buildOutputStyle({ ...base, custom: [] }), plain);
  assert.equal(buildOutputStyle({ ...base, custom: undefined }), plain);
  const last = Number(plain.match(/\n(\d+)\. Reply tiers/)[1]);
  const withCustom = buildOutputStyle({ ...base, custom: customRules });
  assert.ok(withCustom.includes('\n' + (last + 1) + '. ' + customRules[0] + '\n'));
  assert.ok(withCustom.includes('\n' + (last + 2) + '. ' + customRules[1] + '\n'));
});

test('custom rules are never rewritten to satisfy the em-dash ban', () => {
  const kept = 'Keep my dashes \u2014 they are mine \u2013 all of them.';
  const out = buildOutputStyle({ ...base, custom: [kept + '   \n'] });
  assert.ok(out.includes('. ' + kept + '\n'));
});

test('blank custom rules are dropped rather than numbered', () => {
  assert.equal(buildOutputStyle({ ...base, custom: ['', '   ', '\n'] }), buildOutputStyle(base));
});

test('palette fidelity', () => {
  assert.equal(buildPaletteMarkdown('you'), fix('palette.md'));
});

test('rev override lands in the generated-file stamp', () => {
  assert.ok(buildOutputStyle({ ...base, rev: '9.9.9' })
    .includes('<!-- Generated by the talking-to-dave plugin, rev 9.9.9.'));
});

test('docsPath override rewrites both capability-doc references', () => {
  const c = buildOutputStyle({ ...base, docsPath: '/plug/docs/' });
  assert.ok(c.includes('`/plug/docs/desktop-capabilities.md`'));
  assert.ok(c.includes('`/plug/docs/tui-capabilities.md`'));
  assert.ok(!c.includes('`docs/desktop-capabilities.md`'));
});

test('sanitizeName strips markdown and table metacharacters', () => {
  assert.equal(sanitizeName('  A|b`c\\d#e>f*g_h[i]j"k  '), 'Abcdefghijk');
  assert.equal(sanitizeName(''), 'Dave');
});

test('no em or en dashes in any output', () => {
  for (const cfg of Object.values(cases)) {
    assert.doesNotMatch(buildOutputStyle(cfg), /[\u2013\u2014]/);
    assert.doesNotMatch(buildChatPreferences(cfg), /[\u2013\u2014]/);
  }
});
