/* Golden-fixture tests. The fixtures were generated by running the ORIGINAL
 * configurator page's builder logic, so these pin extraction fidelity: for
 * identical inputs, lib/builder.js must reproduce the legacy output byte for
 * byte. The rev and docsPath parameters are the only intended divergences. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildContract, buildChatPreferences, buildPaletteMarkdown, sanitizeName } from '../lib/builder.js';

const here = dirname(fileURLToPath(import.meta.url));
const fix = (name) => readFileSync(join(here, 'fixtures', name), 'utf8');

const base = {
  name: 'Dave',
  weather: true, forecast: true, tasks: true, docs: true, fold: true,
  decision: true, diff: true, emdash: true, visual: true, interactive: true,
  dlg: 'blockers',
};
const cases = {
  'defaults': { ...base },
  'weather-off': { ...base, weather: false },
  'forecast-off': { ...base, forecast: false },
  'custom-name': { ...base, name: 'Alex', docs: false, dlg: 'free' },
  'dlg-ban': { ...base, dlg: 'ban', tasks: false },
};

for (const [key, cfg] of Object.entries(cases)) {
  test('contract fidelity: ' + key, () => {
    assert.equal(buildContract(cfg), fix(key + '.contract.md'));
  });
  test('chat preferences fidelity: ' + key, () => {
    assert.equal(buildChatPreferences(cfg), fix(key + '.chat-prefs.txt'));
  });
}

test('palette fidelity', () => {
  assert.equal(buildPaletteMarkdown('you'), fix('palette.md'));
});

test('rev override lands in the BEGIN marker', () => {
  assert.ok(buildContract({ ...base, rev: '9.9.9' }).startsWith('<!-- BEGIN presentation-contract rev=9.9.9.'));
});

test('docsPath override rewrites both capability-doc references', () => {
  const c = buildContract({ ...base, docsPath: '/plug/docs/' });
  assert.ok(c.includes('`/plug/docs/desktop-capabilities.md`'));
  assert.ok(c.includes('`/plug/docs/tui-capabilities.md`'));
  assert.ok(!c.includes('`docs/desktop-capabilities.md`'));
});

test('sanitizeName strips markdown and table metacharacters', () => {
  assert.equal(sanitizeName('  A|b`c\\d#e>f*g_h[i]j"k  '), 'Abcdefghijk');
  assert.equal(sanitizeName(''), 'Dave');
});

test('no em or en dashes in any output', () => {
  for (const cfg of Object.values(cases)) {
    assert.doesNotMatch(buildContract(cfg), /[\u2013\u2014]/);
    assert.doesNotMatch(buildChatPreferences(cfg), /[\u2013\u2014]/);
  }
});
