/* Golden-fixture tests. The fixture bodies came from running the ORIGINAL
 * configurator page's builder logic, so these pin extraction fidelity: for
 * identical inputs, lib/builder.js must reproduce that output byte for byte,
 * now wrapped in the output-style frontmatter the plugin installs. The rev and
 * docsPath parameters are the only intended divergences. */
import test from 'node:test';
import assert from 'node:assert/strict';
import { readFileSync } from 'node:fs';
import { join, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';
import { buildOutputStyle, buildChatPreferences, buildPaletteMarkdown, sanitizeName } from '../lib/builder.js';

const here = dirname(fileURLToPath(import.meta.url));
const fix = (name) => readFileSync(join(here, 'fixtures', name), 'utf8');

const base = {
  name: 'Dave',
  weather: true, forecast: true, tasks: true, docs: true, fold: true,
  decision: true, diff: true, emdash: true, visual: true, interactive: true,
  ids: true,
  queue: 'widgets', serial: false,
  dlg: 'blockers',
};
const cases = {
  'defaults': { ...base },
  'weather-off': { ...base, weather: false },
  'forecast-off': { ...base, forecast: false },
  'custom-name': { ...base, name: 'Alex', docs: false, dlg: 'free' },
  'dlg-ban': { ...base, dlg: 'ban', tasks: false },
  'ids-off': { ...base, ids: false },
};
const customRules = [
  'Ship notes. When a change lands, name the branch and say whether CI is green.',
  'Never guess at pricing or quotas: look the number up and cite the line you read it from.',
];
const styleCases = {
  ...cases,
  'custom-rules': { ...base, custom: customRules },
  'queue-off': { ...base, queue: 'off' },
  'queue-text': { ...base, queue: 'text' },
  'queue-serial': { ...base, serial: true },
};

/* The output style is the only carrier the plugin installs, so its whole file
 * (frontmatter, generated-file stamp, contract body) is what gets pinned. */
for (const [key, cfg] of Object.entries(styleCases)) {
  test('output style fidelity: ' + key, () => {
    assert.equal(buildOutputStyle(cfg), fix(key + '.output-style.md'));
  });
}

for (const [key, cfg] of Object.entries(cases)) {
  test('chat preferences fidelity: ' + key, () => {
    assert.equal(buildChatPreferences(cfg), fix(key + '.chat-prefs.txt'));
  });
}

test('no marker machinery survives in the generated style', () => {
  const s = buildOutputStyle(base);
  assert.ok(!s.includes('BEGIN presentation-contract'));
  assert.ok(!s.includes('END presentation-contract'));
  assert.ok(s.includes('\n\n## Talking to Dave (presentation contract)\n'));
});

test('the output style frontmatter keeps the coding instructions', () => {
  const s = buildOutputStyle(base);
  assert.ok(s.startsWith('---\nname: talking-to-dave\n'));
  assert.match(s, /^keep-coding-instructions: true$/m);
});

test('custom rules continue the numbering and go in verbatim', () => {
  const plain = buildOutputStyle(base);
  assert.equal(buildOutputStyle({ ...base, custom: [] }), plain);
  assert.equal(buildOutputStyle({ ...base, custom: undefined }), plain);
  const last = Number(plain.match(/\n(\d+)\. Reply tiers/)[1]);
  const withCustom = buildOutputStyle({ ...base, custom: customRules });
  assert.ok(withCustom.includes('\n' + (last + 1) + '. ' + customRules[0] + '\n'));
  assert.ok(withCustom.includes('\n' + (last + 2) + '. ' + customRules[1] + '\n'));
});

test('custom rules are never rewritten to satisfy the em-dash ban', () => {
  const kept = 'Keep my dashes \u2014 they are mine \u2013 all of them.';
  const out = buildOutputStyle({ ...base, custom: [kept + '   \n'] });
  assert.ok(out.includes('. ' + kept + '\n'));
});

test('blank custom rules are dropped rather than numbered', () => {
  assert.equal(buildOutputStyle({ ...base, custom: ['', '   ', '\n'] }), buildOutputStyle(base));
});

test('palette fidelity', () => {
  assert.equal(buildPaletteMarkdown('you'), fix('palette.md'));
});

test('rev override lands in the generated-file stamp', () => {
  assert.ok(buildOutputStyle({ ...base, rev: '9.9.9' })
    .includes('<!-- Generated by the talking-to-dave plugin, rev 9.9.9.'));
});

test('docsPath override rewrites both capability-doc references', () => {
  const c = buildOutputStyle({ ...base, docsPath: '/plug/docs/' });
  assert.ok(c.includes('`/plug/docs/desktop-capabilities.md`'));
  assert.ok(c.includes('`/plug/docs/tui-capabilities.md`'));
  assert.ok(c.includes('`/plug/docs/question-file.md`'));
  assert.ok(!c.includes('`docs/desktop-capabilities.md`'));
});

test('the queue mode swaps footer machinery whole', () => {
  const on = buildOutputStyle(base);
  assert.ok(on.includes('The question queue.'));
  assert.ok(on.includes('The bar is a widget'));
  assert.ok(on.includes('minimal closing line'), 'widgets mode carries the ordering rule');
  assert.ok(on.includes('told in full exactly once'));
  assert.ok(on.includes('|questions|❓|'));
  assert.ok(!on.includes('complete set of what is outstanding'));
  assert.ok(!on.includes('waiting count'));
  assert.ok(!on.includes('One topic at a time (serial)'));
  const off = buildOutputStyle({ ...base, queue: 'off' });
  assert.ok(!off.includes('The question queue.'));
  assert.ok(!off.includes('|questions|'));
  assert.ok(off.includes('complete set of what is outstanding'));
  const text = buildOutputStyle({ ...base, queue: 'text' });
  assert.ok(text.includes('The question queue.'));
  assert.ok(text.includes('Answering is typed'));
  assert.ok(!text.includes('The bar is a widget'));
  assert.ok(!text.includes('minimal closing line'));
  const plain = buildOutputStyle({ ...base, forecast: false });
  assert.ok(plain.includes('the question queue (next rule)'));
  assert.ok(plain.includes('The question queue.'));
});

test('serial adds the one-topic discipline in both queue modes', () => {
  const serial = buildOutputStyle({ ...base, serial: true });
  assert.ok(serial.includes('One topic at a time (serial)'));
  const serialText = buildOutputStyle({ ...base, queue: 'text', serial: true });
  assert.ok(serialText.includes('One topic at a time (serial)'));
  assert.ok(!buildOutputStyle({ ...base, queue: 'off', serial: true }).includes('One topic at a time'));
});

test('every footer variant names the provisional-render state exactly once', () => {
  const variants = [base, { ...base, queue: 'off' }, { ...base, forecast: false }, { ...base, forecast: false, queue: 'off' }];
  for (const cfg of variants) {
    const s = buildOutputStyle(cfg);
    assert.equal((s.match(/render provisionally/g) || []).length, 1,
      'forecast=' + cfg.forecast + ' queue=' + cfg.queue);
  }
});

test('the ids toggle swaps the naming discipline whole', () => {
  const on = buildOutputStyle(base);
  assert.ok(on.includes('IDs carry names.'));
  assert.ok(on.includes('When unsure, name it.'));
  assert.ok(!on.includes('IDs never appear bare'));
  const off = buildOutputStyle({ ...base, ids: false });
  assert.ok(!off.includes('IDs carry names.'));
  assert.ok(off.includes('IDs never appear bare'));
  assert.ok(buildChatPreferences(base).includes('short human name'));
  assert.ok(!buildChatPreferences({ ...base, ids: false }).includes('short human name'));
});

test('legacy boolean queue values coerce to the mode strings', () => {
  assert.equal(buildOutputStyle({ ...base, queue: true }), buildOutputStyle(base));
  assert.equal(buildOutputStyle({ ...base, queue: false }), buildOutputStyle({ ...base, queue: 'off' }));
});

test('sanitizeName strips markdown and table metacharacters', () => {
  assert.equal(sanitizeName('  A|b`c\\d#e>f*g_h[i]j"k  '), 'Abcdefghijk');
  assert.equal(sanitizeName(''), 'Dave');
});

test('no em or en dashes in any output', () => {
  for (const cfg of Object.values(cases)) {
    assert.doesNotMatch(buildOutputStyle(cfg), /[\u2013\u2014]/);
    assert.doesNotMatch(buildChatPreferences(cfg), /[\u2013\u2014]/);
  }
});
